spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=BasketballMatch;encrypt=true;trustServerCertificate=true
    username: sa
    password: 333333SASEsm
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect